import { BRAND, BRAND_CITY } from './brand';

/**
 * The privacy policy, as data.
 *
 * One source feeds two surfaces: the in-app screen (App Store 5.1.1, Play
 * « Data safety ») and the hosted HTML page the store listings link to
 * (`legal/privacy.html`, generated by `npm run legal:build` and kept in sync by
 * tests/legal.test.cjs). Writing it twice is how the two versions drift apart.
 *
 * Facts below describe what the code actually does — no GPS, no ads SDK, no
 * analytics — and must be updated when that changes.
 */

/** Publisher identity for the store listings; set in the EAS production environment. */
export const LEGAL_PUBLISHER = (process.env.EXPO_PUBLIC_LEGAL_PUBLISHER ?? '').trim();
/** Contact for privacy requests; set in the EAS production environment. */
export const LEGAL_EMAIL = (process.env.EXPO_PUBLIC_LEGAL_EMAIL ?? '').trim();

export const PRIVACY_UPDATED_AT = '22 septembre 2026';

export interface LegalSection {
    title: string;
    paragraphs: string[];
    bullets?: string[];
}

const publisher = LEGAL_PUBLISHER || `l'éditeur de ${BRAND}`;
const contact = LEGAL_EMAIL
    ? `par email à ${LEGAL_EMAIL}`
    : `depuis l'application (Profil → Aide)`;

export const PRIVACY_POLICY: readonly LegalSection[] = [
    {
        title: 'Qui est responsable de vos données',
        paragraphs: [
            `${BRAND} est une application de commande et de livraison de repas à ${BRAND_CITY}. Le responsable du traitement de vos données est ${publisher}. Vous pouvez le joindre ${contact}.`,
            `Cette politique décrit les données que l'application collecte, pourquoi, avec qui elles sont partagées et comment les faire supprimer. Elle s'applique conformément à la réglementation tchadienne relative à la protection des données à caractère personnel.`,
        ],
    },
    {
        title: 'Les données que nous collectons',
        paragraphs: ['Nous ne collectons que ce qui est nécessaire pour vous livrer.'],
        bullets: [
            `Compte : adresse email, mot de passe (conservé uniquement sous forme chiffrée), nom facultatif, numéro de téléphone de livraison.`,
            `Commandes : nom et téléphone du destinataire, adresse et quartier de livraison, consigne éventuelle, plats commandés, montant, billet remis pour la monnaie, horodatages et statut.`,
            `Appareil : un jeton technique de notification (Apple, Google ou Expo) et le type d'appareil, afin de vous prévenir de l'avancement de votre commande.`,
            `Données locales : panier, adresses enregistrées et favoris sont stockés sur votre téléphone uniquement et effacés à la déconnexion.`,
        ],
    },
    {
        title: 'Ce que nous ne faisons pas',
        paragraphs: [],
        bullets: [
            `Aucune géolocalisation GPS : l'adresse est celle que vous saisissez.`,
            `Aucune publicité, aucun réseau publicitaire, aucun suivi entre applications.`,
            `Aucune vente ni location de vos données.`,
            `Aucun paiement en ligne : le règlement se fait en espèces à la livraison, l'application ne traite aucune donnée bancaire.`,
        ],
    },
    {
        title: 'Pourquoi nous les utilisons',
        paragraphs: [],
        bullets: [
            `Préparer et livrer votre commande (exécution du contrat).`,
            `Vous informer de son avancement par notification.`,
            `Répondre à vos demandes d'assistance.`,
            `Assurer la sécurité du service et prévenir les abus.`,
            `Tenir la comptabilité des restaurants partenaires (obligation légale).`,
        ],
    },
    {
        title: 'Avec qui elles sont partagées',
        paragraphs: [],
        bullets: [
            `Le restaurant que vous avez choisi reçoit votre nom, votre téléphone, votre adresse et votre consigne : il prépare et livre lui-même votre commande.`,
            `Supabase héberge la base de données et l'authentification sur des serveurs situés dans l'Union européenne.`,
            `Les notifications transitent par les services d'Apple, de Google et d'Expo selon votre appareil.`,
            `Si vous contactez l'assistance sur WhatsApp, l'échange est régi par la politique de WhatsApp ; l'application n'y envoie rien sans votre action.`,
        ],
    },
    {
        title: 'Combien de temps nous les gardons',
        paragraphs: [],
        bullets: [
            `Votre compte et vos coordonnées : tant que le compte existe.`,
            `Vos commandes : après suppression du compte, elles sont conservées anonymisées (sans nom, téléphone, adresse ni consigne) pour la comptabilité du restaurant.`,
            `Les jetons de notification : supprimés à la déconnexion ou à la suppression du compte.`,
            `Les journaux techniques de notification : quelques semaines au plus, pour diagnostiquer les échecs d'envoi.`,
        ],
    },
    {
        title: 'Vos droits',
        paragraphs: [
            `Vous pouvez accéder à vos données, les corriger et les supprimer. La suppression du compte se fait directement dans l'application : Profil → Supprimer mon compte. Elle est immédiate et définitive dès qu'aucune commande n'est en cours.`,
            `Pour toute autre demande (accès, rectification, opposition), contactez-nous ${contact}. Nous répondons dans un délai d'un mois.`,
        ],
    },
    {
        title: 'Sécurité',
        paragraphs: [
            `Les échanges sont chiffrés (HTTPS). Chaque compte ne peut lire que ses propres commandes grâce à des règles d'accès appliquées par la base de données. Les mots de passe ne sont jamais stockés en clair.`,
        ],
    },
    {
        title: 'Mineurs',
        paragraphs: [`${BRAND} s'adresse aux personnes majeures. Nous ne collectons pas sciemment de données concernant des mineurs.`],
    },
    {
        title: 'Modifications',
        paragraphs: [`Cette politique a été mise à jour le ${PRIVACY_UPDATED_AT}. En cas de changement important, vous en serez informé dans l'application.`],
    },
];
