/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./src/components/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#474746",
        "primary-container": "#3d0600",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#8c1800",
        "surface-tint": "#FF5733",
        "inverse-surface": "#313030",
        "on-surface": "#1c1b1b",
        "on-tertiary-container": "#838486",
        "on-secondary-container": "#636262",
        "tertiary-fixed": "#e2e2e4",
        "tertiary-fixed-dim": "#c6c6c8",
        "surface-container-high": "#eae7e7",
        "tertiary-container": "#1a1c1d",
        "on-secondary": "#ffffff",
        "surface-variant": "#e5e2e1",
        "primary-fixed-dim": "#ffb4a4",
        "on-primary-container": "#ec4a27",
        "inverse-on-surface": "#f3f0ef",
        "on-tertiary-fixed": "#1a1c1d",
        "outline": "#747878",
        "surface-bright": "#fcf9f8",
        "primary-fixed": "#ffdad3",
        "surface-container": "#f0eded",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#3d0600",
        "secondary-fixed": "#e5e2e1",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#e2dfde",
        "inverse-primary": "#ffb4a4",
        "tertiary": "#1c1b1b",
        "on-background": "#1c1b1b",
        "on-error": "#ffffff",
        "primary": "#1c1b1b",
        // Warm neutral ramp (replaces the #747878 / #a1a1aa / #9ca3af drift).
        "ink": "#1c1b1b",
        "ink-muted": "#5f5e5e",
        "ink-faint": "#8d8a87",
        "ink-disabled": "#c4c7c7",
        "hairline": "#e7e3e1",
        "accent": "#FF5733",
        "accent-tint": "#FFEDE7",
        "danger": "#ba1a1a",
        "danger-tint": "#ffdad6",
        // Fill aliases onto the warm ramp (used by tracking/order-confirmed/offline).
        "fill": "#f6f3f2",
        "fill-strong": "#e5e2e1",
        "on-surface-variant": "#444748",
        "surface-container-low": "#f6f3f2",
        "surface": "#fcf9f8",
        "background": "#fcf9f8",
        "outline-variant": "#c4c7c7",
        "secondary": "#5f5e5e",
        "surface-container-highest": "#e5e2e1",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#c8c6c5",
        "surface-dim": "#dcd9d9",
        "on-secondary-fixed": "#1c1b1b"
      },
      borderRadius: {
        // Single corner language: pills = rounded-full, thumbnails = 2xl(16),
        // cards/rows = 3xl(24), feature/hero/sheets = sheet(28).
        sheet: '28px',
      },
      fontFamily: {
        // Real weight ramp mapped to the faces actually loaded in app/_layout.tsx.
        // (Bare `manrope`/`inter` stay as aliases so any un-migrated class still renders.)
        display: ['Manrope_800ExtraBold'],
        title: ['Manrope_700Bold'],
        heading: ['Manrope_600SemiBold'],
        subheading: ['Manrope_500Medium'],
        body: ['Inter_400Regular'],
        label: ['Inter_500Medium'],
        labelbold: ['Inter_600SemiBold'],
        manrope: ['Manrope', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
