const { withInfoPlist, createRunOncePlugin } = require('@expo/config-plugins');

const pkg = require('../../package.json');

/**
 * Enables Live Activities on the main app target.
 *
 * The actual Dynamic Island / Live Activity widget target is generated by
 * `@bacons/apple-targets` from the `targets/widget` folder — this plugin only
 * flips the Info.plist flag the system requires for `Activity.request()` to work.
 *
 * (The previous version also copied Swift files into ios/ChadDeliveryWidget but
 * never registered an Xcode target, which is why nothing was ever displayed.)
 */
const withLiveActivity = (config) => {
    return withInfoPlist(config, (config) => {
        config.modResults.NSSupportsLiveActivities = true;
        return config;
    });
};

module.exports = createRunOncePlugin(withLiveActivity, pkg.name, pkg.version);
